### ISSUE TITLE
Flesheater image url typo

### ISSUE THREAD

**Issue by j78FG86l69VA58U** [markblokpoel/battlescribe-custom-warcry-export#10]
By default the flesheater-courts rune logo seems broken.
The HTML links to assets/runemarks/white/flesheater-court.svg but the file is called flesheater-courts.svg (with an s at the end)

**Comment by markblokpoel** [comment]
Should be fixed with newest data and cards, see also: https://github.com/markblokpoel/battlescribe-custom-warcry-export/issues/6#issuecomment-950608844
