### ISSUE TITLE
Runemark white flesh eater court

### ISSUE THREAD

**Issue by Dreadaxe** [markblokpoel/battlescribe-custom-warcry-export#6]
Seem to point to different address
battlescribe-custom-warcry-export-main/output/assets/runemarks/white/flesheater-court.svg
battlescribe-custom-warcry-export-main/output/assets/runemarks/white/flesh-eater-court.svg
battlescribe-custom-warcry-export-main/output/assets/runemarks/white/flesheater-courts.svg

**Comment by markblokpoel** [comment]
Let me check this against newest bs data, should be fixed.

**Comment by markblokpoel** [comment]
Seems to work correctly with the newest dataset version (v8 for FeC). Not sure if this has been pushed to the public repository, might require manually downloading and adding the data from the warcry repository. Closing this issue.
