### ISSUE TITLE
Necromancer

### ISSUE THREAD

**Issue by Dreadaxe** [markblokpoel/battlescribe-custom-warcry-export#8]
![image](https://user-images.githubusercontent.com/13752505/138613488-713d9c4e-6b00-4e7f-a162-61ee0810967d.png)

**Comment by markblokpoel** [comment]
Thanks for posting. This is some of the longest ability text I've seen yet.. I've allowed for a slightly smaller font size to accommodate all the text. Fixed in 334c1a9.
